stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "arala/authfortress"
  SSH_USER: "azureuser"
  SSH_HOST: "4.233.222.126"
  REMOTE_PATH: "/home/azureuser/Auth-Fortress"

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

build_job:
  stage: build
  tags:
    - docker
  script:
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker tag $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:latest
  only:
    - master

deploy_job:
  stage: deploy
  tags:
    - deploy
  script:
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "mkdir -p $REMOTE_PATH/vault"
    - echo "$VAULT_ROLE_ID" | ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cat > $REMOTE_PATH/vault/role_id"
    - echo "$VAULT_SECRET_ID" | ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cat > $REMOTE_PATH/vault/secret_id"
    - scp -o StrictHostKeyChecking=no docker-compose.yml $SSH_USER@$SSH_HOST:$REMOTE_PATH
    # - scp -o StrictHostKeyChecking=no -r ./templates $SSH_USER@$SSH_HOST:$REMOTE_PATH
    # - scp -o StrictHostKeyChecking=no vault-agent-config.hcl $SSH_USER@$SSH_HOST:$REMOTE_PATH
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
        cd $REMOTE_PATH &&
        git pull origin master &&
        docker-compose down --volumes --remove-orphans &&
        docker-compose pull 
      "

    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
        sudo systemctl start authfortress.service &&
        sudo systemctl start auth-fortress_db.service &&
        sudo systemctl start auth-fortress_nginx.service &&
      "
    
  only:
    - master
